import { createContext, useContext, useState, ReactNode, useCallback } from 'react';

// Define the available languages - updated to include all 10 languages
type Language = 'ro' | 'en' | 'fr' | 'de' | 'es' | 'it' | 'pt' | 'nl' | 'sv' | 'da';

// Translation map - expanded for new system and all pages
const translations = {
  ro: {
    // Common
    'common.loading': 'Se încarcă...',
    'common.error': 'Eroare',
    'common.success': 'Succes',
    'common.save': 'Salvează',
    'common.cancel': 'Anulează',
    'common.delete': 'Șterge',
    'common.edit': 'Editează',
    'common.back': 'Înapoi',
    'common.next': 'Următorul',
    'common.submit': 'Trimite',
    'common.search': 'Caută',
    'common.filter': 'Filtrează',
    'common.sort': 'Sortează',
    'common.language': 'Limbă',
    'common.theme': 'Temă',
    'common.dark': 'Întunecată',
    'common.light': 'Luminoasă',
    
    // Navigation
    'nav.courses': 'Cursurile Mele',
    'nav.profile': 'Profil',
    'nav.subscription': 'Abonament',
    'nav.admin': 'Administrare',
    
    // Auth
    'auth.signIn': 'Autentificare',
    'auth.signUp': 'Înregistrare',
    'auth.signOut': 'Deconectare',
    'auth.email': 'Email',
    'auth.password': 'Parolă',
    'auth.forgotPassword': 'Ai uitat parola?',
    'auth.resetPassword': 'Resetează parola',
    'auth.resetPasswordDescription': 'Introdu adresa de email pentru a primi instrucțiuni de resetare',
    'auth.confirmPassword': 'Confirmă parola',
    'auth.noAccount': 'Nu ai cont?',
    'auth.hasAccount': 'Ai deja cont?',
    'auth.signInError': 'Eroare de autentificare',
    'auth.signUpError': 'Eroare de înregistrare',
    'auth.signInSuccess': 'Autentificare reușită',
    'auth.signUpSuccess': 'Înregistrare reușită',
    'auth.resetPasswordError': 'Eroare la resetarea parolei',
    'auth.resetPasswordEmailSent': 'Email de resetare trimis',
    'auth.checkEmailForReset': 'Verifică-ți emailul pentru instrucțiuni',
    'auth.signedOut': 'Deconectat',
    'auth.comeBackSoon': 'Revino curând!',
    'auth.welcomeBack': 'Bine ai revenit!',
    'auth.accountCreated': 'Contul tău a fost creat',
    'auth.termsAgreement': 'Prin înregistrare, accepți',
    'auth.and': 'și',
    
    // Dashboard
    'dashboard.title': 'Tablou de bord',
    'dashboard.welcome': 'Bine ai venit',
    'dashboard.generationsRemaining': 'Cursuri rămase',
    'dashboard.renewalDate': 'Data reînnoirii',
    'dashboard.recentJobs': 'Cursuri recente',
    'dashboard.viewAll': 'Vezi toate',
    'dashboard.noJobs': 'Nu ai cursuri recente',
    'dashboard.startGenerating': 'Începe să generezi',
    'dashboard.emptyState': 'Creează primul tău curs cu AI pentru a începe.',
    
    // Generate - Updated for new system
    'generate.title': 'Generează curs nou',
    'generate.subtitle': 'Creează materiale complete de curs în 7 pași automatizați',
    'generate.form.title': 'Configurare curs',
    'generate.form.description': 'Completează detaliile pentru generarea automată a materialelor',
    'generate.form.language': 'Limba cursului',
    'generate.form.selectLanguage': 'Selectează limba',
    'generate.form.subject': 'Subiectul cursului',
    'generate.form.subjectPlaceholder': 'ex. Management de proiect, Marketing digital...',
    'generate.form.level': 'Nivelul cursului',
    'generate.form.selectLevel': 'Selectează nivelul',
    'generate.form.beginner': 'Începător',
    'generate.form.intermediate': 'Intermediar',
    'generate.form.advanced': 'Avansat',
    'generate.form.audience': 'Publicul țintă',
    'generate.form.selectAudience': 'Selectează publicul',
    'generate.form.students': 'Studenți',
    'generate.form.professionals': 'Profesioniști',
    'generate.form.managers': 'Manageri',
    'generate.form.duration': 'Durata cursului',
    'generate.form.selectDuration': 'Selectează durata',
    'generate.form.30min': '30 minute',
    'generate.form.1h': '1 oră',
    'generate.form.2h': '2 ore',
    'generate.form.4h': '4 ore',
    'generate.form.8h': '8 ore',
    'generate.form.tone': 'Tonul cursului',
    'generate.form.selectTone': 'Selectează tonul',
    'generate.form.socratic': 'Socratic',
    'generate.form.energizing': 'Energizant',
    'generate.form.funny': 'Haios',
    'generate.form.professional': 'Profesional',
    'generate.form.submit': 'Generează cursul',
    'generate.form.submitting': 'Se generează...',
    'generate.error.noGenerationsLeft': 'Nu mai ai cursuri disponibile',
    'generate.error.upgradeOrWait': 'Actualizează planul sau așteaptă reînnoirea',
    'generate.error.formIncomplete': 'Te rugăm să completezi toate câmpurile',
    'generate.error.failed': 'Generarea a eșuat',
    'generate.success.started': 'Generarea a început',
    'generate.info.timeEstimate': 'Generarea poate dura 15-30 minute',
    'generate.info.notification': 'Vei fi notificat când materialele sunt gata',
    'generate.info.remaining': 'Cursuri rămase',
    'generate.info.youHave': 'Ai',
    'generate.info.generationsLeft': 'cursuri rămase în acest ciclu',
    'generate.info.courses': 'cursuri/lună',
    
    // Progress - Updated for 7-step process
    'progress.title': 'Progres generare',
    'progress.status': 'Status',
    'progress.created': 'Creat la',
    'progress.pending': 'În așteptare',
    'progress.processing': 'În procesare',
    'progress.completed': 'Completat',
    'progress.failed': 'Eșuat',
    'progress.retry': 'Încearcă din nou',
    'progress.cancel': 'Anulează',
    'progress.viewMaterials': 'Vezi materialele',
    'progress.viewProgress': 'Vezi progresul',
    'progress.viewStatus': 'Vezi statusul',
    'progress.details': 'Detalii generare',
    'progress.error': 'Eroare',
    'progress.step': 'Pasul',
    'progress.timeEstimate': 'Estimare timp',
    'progress.cancelled': 'Anulat',
    'progress.jobCancelled': 'Generarea a fost anulată',
    'progress.retrying': 'Se reîncearcă',
    'progress.jobRetrying': 'Generarea se reîncearcă',
    'progress.confirmCancel': 'Ești sigur că vrei să anulezi generarea?',
    'progress.cancelFailed': 'Anularea a eșuat',
    'progress.retryFailed': 'Reîncercarea a eșuat',
    'progress.generatingCourse': 'Se generează cursul',
    'progress.step1': 'Structură + Obiective + Agendă',
    'progress.step2': 'Slide-uri de prezentare',
    'progress.step3': 'Manual facilitator',
    'progress.step4': 'Manual participant',
    'progress.step5': 'Activități și exerciții',
    'progress.step6': 'Instrumente de evaluare',
    'progress.step7': 'Resurse suplimentare',
    
    // Materials - Updated for new file types
    'materials.title': 'Materiale generate',
    'materials.downloadAll': 'Descarcă toate',
    'materials.expiryNote': 'Link-urile de descărcare expiră în 72 ore',
    'materials.expiryWarning': 'Atenție! Link-urile expiră în curând',
    'materials.expiryDate': 'Data expirării',
    'materials.noMaterials': 'Nu există materiale disponibile',
    'materials.regenerate': 'Regenerează',
    'materials.download': 'Descarcă',
    'materials.preparing': 'Se pregătește',
    'materials.checkProgress': 'Verifică progresul',
    'materials.untitledCourse': 'Curs fără titlu',
    'materials.courseAgenda': 'Agenda și structura cursului',
    'materials.presentationSlides': 'Slide-uri pentru prezentare',
    'materials.courseMaterial': 'Material de curs',
    'materials.noMaterialsDescription': 'Materialele se generează încă. Verifică progresul pentru mai multe detalii.',
    'materials.types.foundation': 'Structură și Obiective',
    'materials.types.slides': 'Slide-uri Prezentare',
    'materials.types.facilitator': 'Manual Facilitator',
    'materials.types.participant': 'Manual Participant',
    'materials.types.activities': 'Activități și Exerciții',
    'materials.types.evaluation': 'Instrumente Evaluare',
    'materials.types.resources': 'Resurse Suplimentare',
    
    // Settings
    'settings.title': 'Setări cont',
    'settings.description': 'Gestionează contul și abonamentul tău',
    'settings.account': 'Cont',
    'settings.subscription': 'Abonament',
    'settings.security': 'Securitate',
    'settings.accountDetails': 'Detalii cont',
    'settings.accountDetailsDescription': 'Informațiile de bază ale contului tău',
    'settings.accountCreated': 'Cont creat',
    'settings.currentPassword': 'Parola curentă',
    'settings.newPassword': 'Parola nouă',
    'settings.confirmPassword': 'Confirmă parola',
    'settings.updatePassword': 'Actualizează parola',
    'settings.changePassword': 'Schimbă parola',
    'settings.changePasswordDescription': 'Actualizează parola pentru securitate sporită',
    'settings.deleteAccount': 'Șterge contul',
    'settings.deleteAccountDescription': 'Șterge permanent contul și toate datele',
    'settings.deleteAccountWarning': 'Această acțiune nu poate fi anulată. Toate datele vor fi șterse permanent.',
    'settings.warning': 'Atenție',
    'settings.passwordUpdated': 'Parola actualizată',
    'settings.passwordUpdateSuccess': 'Parola a fost actualizată cu succes',
    'settings.passwordUpdateError': 'Eroare actualizare parolă',
    'settings.passwordUpdateFailed': 'Actualizarea parolei a eșuat',
    
    // Subscription - Updated for new plans
    'subscription.free': 'Gratuit',
    'subscription.basic': 'Basic',
    'subscription.pro': 'Pro',
    'subscription.enterprise': 'Enterprise',
    'subscription.monthly': '/lună',
    'subscription.choosePlan': 'Alege un plan',
    'subscription.currentPlan': 'Planul tău actual',
    'subscription.currentPlanDescription': 'Detaliile abonamentului tău curent',
    'subscription.features': 'Caracteristici',
    'subscription.upgrade': 'Actualizează',
    'subscription.downgrade': 'Retrogradează',
    'subscription.cancel': 'Anulează',
    'subscription.switch': 'Schimbă',
    'subscription.manage': 'Gestionează abonamentul',
    'subscription.availablePlans': 'Planuri disponibile',
    'subscription.popular': 'Popular',
    'subscription.billingInfo': 'Informații facturare',
    'subscription.billingManagedByStripe': 'Facturarea este gestionată prin Stripe pentru securitate maximă',
    'subscription.confirmCancel': 'Ești sigur că vrei să anulezi abonamentul?',
    'subscription.cancelSuccess': 'Abonament anulat',
    'subscription.cancelMessage': 'Abonamentul a fost anulat cu succes',
    'subscription.cancelError': 'Eroare anulare',
    'subscription.cancelFailed': 'Anularea abonamentului a eșuat',
    'subscription.upgradeError': 'Eroare actualizare',
    'subscription.upgradeFailed': 'Actualizarea abonamentului a eșuat',
    'subscription.checkoutError': 'Eroare checkout',
    'subscription.checkoutSuccess': 'Checkout reușit',
    'subscription.checkoutSuccessMessage': 'Abonamentul a fost actualizat cu succes',
    'subscription.checkoutCancelled': 'Checkout anulat',
    'subscription.checkoutCancelledMessage': 'Procesul de plată a fost anulat',
    'subscription.renewsAutomatically': 'Se reînnoiește automat',
    'subscription.features.fullGeneration': 'Generare completă cursuri',
    'subscription.features.downloads': 'Descărcări nelimitate',
    'subscription.features.support': 'Suport standard',
    'subscription.features.prioritySupport': 'Suport prioritar',
    'subscription.features.dedicatedSupport': 'Suport dedicat',
    'subscription.features.extendedDownloads': 'Descărcări extinse (7 zile)',
    'subscription.features.priorityProcessing': 'Procesare prioritară',
    
    // Plans - Updated for new pricing
    'plans.basic.name': 'Basic',
    'plans.basic.price': '9€',
    'plans.basic.description': '1 curs complet/lună',
    'plans.pro.name': 'Pro',
    'plans.pro.price': '39€',
    'plans.pro.description': '5 cursuri/lună',
    'plans.enterprise.name': 'Enterprise',
    'plans.enterprise.price': '89€',
    'plans.enterprise.description': '20 cursuri/lună',
    
    // Landing Page
    'landing.title': 'Sistem Optimizat de Generare Cursuri',
    'landing.subtitle': 'Creează materiale educaționale complete în 7 pași automatizați cu AI',
    'landing.aiPowered': 'Alimentat de AI',
    'landing.getStarted': 'Începe acum',
    'landing.learnMore': 'Află mai multe',
    'landing.about': 'Despre',
    'landing.howItWorks': 'Cum funcționează',
    'landing.howItWorksSubtitle': 'Procesul nostru simplu în 3 pași pentru generarea cursurilor',
    'landing.pricing': 'Prețuri',
    'landing.pricingSubtitle': 'Alege planul potrivit pentru nevoile tale',
    'landing.faq': 'Întrebări frecvente',
    'landing.contact': 'Contact',
    'landing.footer.copyright': 'Toate drepturile rezervate',
    'landing.footer.terms': 'Termeni și condiții',
    'landing.footer.privacy': 'Politică de confidențialitate',
    'landing.step1Title': 'Configurează cursul',
    'landing.step1Description': 'Alege limba, subiectul, nivelul și durata cursului',
    'landing.step2Title': 'AI generează materialele',
    'landing.step2Description': 'Sistemul nostru creează automat toate materialele în 7 pași',
    'landing.step3Title': 'Descarcă și folosește',
    'landing.step3Description': 'Primești materiale complete gata de utilizare',
    'landing.benefits': 'Beneficiile platformei',
    'landing.benefitsSubtitle': 'De ce să alegi Automator.ro pentru cursurile tale',
    'landing.benefit1Title': 'Economisește timp',
    'landing.benefit1Description': 'Generează cursuri complete în minute, nu în zile',
    'landing.benefit2Title': 'Calitate profesională',
    'landing.benefit2Description': 'Materiale create cu standardele industriei',
    'landing.benefit3Title': '10 limbi disponibile',
    'landing.benefit3Description': 'Suport pentru toate limbile europene majore',
    'landing.benefit4Title': 'Pentru orice audiență',
    'landing.benefit4Description': 'Adaptabil pentru studenți, profesioniști și manageri',
    'landing.ctaTitle': 'Gata să începi?',
    'landing.ctaSubtitle': 'Alătură-te miilor de educatori care folosesc deja Automator.ro',
    'landing.startNow': 'Începe acum',
    'landing.viewAllPlans': 'Vezi toate planurile',
    
    // About Page
    'about.title': 'Despre Automator.ro',
    'about.subtitle': 'Misiunea noastră și metodologia de 7 pași',
    'about.mission.title': 'Misiunea noastră',
    'about.mission.description1': 'Automator.ro transformă modul în care se creează materialele educaționale, oferind o platformă AI care generează cursuri complete și profesionale în timp record.',
    'about.mission.description2': 'Credem că educația de calitate trebuie să fie accesibilă și ușor de creat pentru toți educatorii, indiferent de experiența lor în design instrucțional.',
    'about.methodology.title': 'Metodologia de 7 pași',
    'about.methodology.subtitle': 'Procesul nostru sistematic pentru crearea cursurilor complete',
    'about.step1Description': 'Definirea structurii cursului, obiectivelor de învățare și agendei detaliate',
    'about.step2Description': 'Crearea slide-urilor de prezentare cu conținut vizual și note pentru prezentator',
    'about.step3Description': 'Dezvoltarea manualului complet pentru facilitator cu ghiduri și instrucțiuni',
    'about.step4Description': 'Generarea manualului participantului cu exerciții și spații pentru notițe',
    'about.step5Description': 'Crearea activităților interactive, jocurilor de rol și studiilor de caz',
    'about.step6Description': 'Dezvoltarea instrumentelor de evaluare pre, durante și post curs',
    'about.step7Description': 'Compilarea resurselor suplimentare pentru dezvoltarea continuă',
    'about.whyChoose.title': 'De ce să alegi Automator.ro',
    'about.whyChoose.subtitle': 'Avantajele care ne diferențiază de alte soluții',
    'about.advantage1.title': 'Rapiditate',
    'about.advantage1.description': 'Generează cursuri complete în 15-30 minute',
    'about.advantage2.title': 'Completitudine',
    'about.advantage2.description': 'Toate materialele necesare într-un singur loc',
    'about.advantage3.title': 'Multilingv',
    'about.advantage3.description': 'Suport pentru 10 limbi europene',
    'about.advantage4.title': 'Personalizabil',
    'about.advantage4.description': 'Adaptat pentru diferite audiențe și niveluri',
    'about.advantage5.title': 'Profesional',
    'about.advantage5.description': 'Standardele industriei în design instrucțional',
    'about.advantage6.title': 'Accesibil',
    'about.advantage6.description': 'Prețuri competitive pentru toate bugetele',
    'about.cta.title': 'Începe să creezi cursuri astăzi',
    'about.cta.description': 'Alătură-te comunității de educatori care folosesc AI pentru a crea materiale de calitate',
    'about.cta.startNow': 'Începe acum',
    'about.cta.viewPricing': 'Vezi prețurile',
    
    // Pricing Page
    'pricing.title': 'Planuri și prețuri',
    'pricing.subtitle': 'Alege planul potrivit pentru nevoile tale educaționale',
    'pricing.feature.allLanguages': 'Toate cele 10 limbi',
    'pricing.faq.title': 'Întrebări frecvente',
    'pricing.faq.subtitle': 'Răspunsuri la întrebările comune despre planuri',
    'pricing.faq.q1': 'Pot să îmi schimb planul oricând?',
    'pricing.faq.a1': 'Da, poți actualiza sau retrograda planul oricând. Modificările se aplică imediat.',
    'pricing.faq.q2': 'Ce se întâmplă dacă depășesc limita de cursuri?',
    'pricing.faq.a2': 'Vei fi notificat când te apropii de limită. Poți actualiza planul pentru cursuri suplimentare.',
    'pricing.faq.q3': 'Sunt disponibile reduceri pentru instituții?',
    'pricing.faq.a3': 'Da, oferim reduceri speciale pentru școli și universități. Contactează-ne pentru detalii.',
    'pricing.faq.q4': 'Pot să anullez abonamentul oricând?',
    'pricing.faq.a4': 'Da, poți anula abonamentul oricând. Nu există penalități sau taxe de anulare.',
    'pricing.contact.title': 'Ai nevoie de un plan personalizat?',
    'pricing.contact.description': 'Contactează-ne pentru soluții enterprise sau planuri personalizate',
    'pricing.contact.button': 'Contactează-ne',
    
    // Contact Page
    'contact.title': 'Contactează-ne',
    'contact.subtitle': 'Suntem aici să te ajutăm cu orice întrebări sau sugestii',
    'contact.info.email': 'Email',
    'contact.info.emailDescription': 'Trimite-ne un email pentru întrebări generale',
    'contact.info.phone': 'Telefon',
    'contact.info.phoneDescription': 'Sună-ne pentru suport urgent',
    'contact.info.address': 'Adresa',
    'contact.info.addressDescription': 'Biroul nostru din București',
    'contact.form.title': 'Trimite-ne un mesaj',
    'contact.form.description': 'Completează formularul și îți vom răspunde în cel mai scurt timp',
    'contact.form.name': 'Nume',
    'contact.form.namePlaceholder': 'Numele tău complet',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'adresa@email.com',
    'contact.form.subject': 'Subiect',
    'contact.form.subjectPlaceholder': 'Despre ce vrei să vorbești?',
    'contact.form.message': 'Mesaj',
    'contact.form.messagePlaceholder': 'Descrie-ne întrebarea sau sugestia ta...',
    'contact.form.send': 'Trimite mesajul',
    'contact.form.sending': 'Se trimite...',
    'contact.form.success': 'Mesaj trimis',
    'contact.form.successMessage': 'Îți mulțumim pentru mesaj. Îți vom răspunde în curând.',
    'contact.faq.title': 'Întrebări frecvente',
    'contact.faq.subtitle': 'Răspunsuri rapide la întrebările comune',
    'contact.faq.q1': 'Cât durează să generez un curs?',
    'contact.faq.a1': 'Generarea unui curs durează între 15-30 minute, în funcție de complexitate.',
    'contact.faq.q2': 'Pot edita materialele generate?',
    'contact.faq.a2': 'Da, toate materialele sunt editabile și pot fi personalizate după nevoile tale.',
    'contact.faq.q3': 'În ce formate primesc materialele?',
    'contact.faq.a3': 'Materialele sunt disponibile în format DOCX pentru texte și PPTX pentru prezentări.',
    
    // 404 Page
    '404.title': 'Pagina nu a fost găsită',
    '404.description': 'Ne pare rău, pagina pe care o cauți nu există.',
    '404.suggestion': 'Poate ai greșit adresa sau pagina a fost mutată.',
    '404.goHome': 'Înapoi acasă',
    '404.contact': 'Contactează-ne',
    '404.goBack': 'Înapoi',
    
    // Languages
    'languages.ro': 'Română',
    'languages.en': 'English',
    'languages.fr': 'Français',
    'languages.de': 'Deutsch',
    'languages.es': 'Español',
    'languages.it': 'Italiano',
    'languages.pt': 'Português',
    'languages.nl': 'Nederlands',
    'languages.sv': 'Svenska',
    'languages.da': 'Dansk',
  },
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.language': 'Language',
    'common.theme': 'Theme',
    'common.dark': 'Dark',
    'common.light': 'Light',
    
    // Navigation
    'nav.courses': 'My Courses',
    'nav.profile': 'Profile',
    'nav.subscription': 'Subscription',
    'nav.admin': 'Admin',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.signOut': 'Sign Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPasswordDescription': 'Enter your email address to receive reset instructions',
    'auth.confirmPassword': 'Confirm Password',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.signInError': 'Sign in error',
    'auth.signUpError': 'Sign up error',
    'auth.signInSuccess': 'Sign in successful',
    'auth.signUpSuccess': 'Sign up successful',
    'auth.resetPasswordError': 'Password reset error',
    'auth.resetPasswordEmailSent': 'Password reset email sent',
    'auth.checkEmailForReset': 'Check your email for reset instructions',
    'auth.signedOut': 'Signed out',
    'auth.comeBackSoon': 'Come back soon!',
    'auth.welcomeBack': 'Welcome back!',
    'auth.accountCreated': 'Your account has been created',
    'auth.termsAgreement': 'By registering, you agree to our',
    'auth.and': 'and',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.generationsRemaining': 'Courses remaining',
    'dashboard.renewalDate': 'Renewal date',
    'dashboard.recentJobs': 'Recent courses',
    'dashboard.viewAll': 'View all',
    'dashboard.noJobs': 'You have no recent courses',
    'dashboard.startGenerating': 'Start generating',
    'dashboard.emptyState': 'Create your first AI-powered course to get started.',
    
    // Generate - Updated for new system
    'generate.title': 'Generate New Course',
    'generate.subtitle': 'Create complete course materials in 7 automated steps',
    'generate.form.title': 'Course Configuration',
    'generate.form.description': 'Fill in the details for automatic material generation',
    'generate.form.language': 'Course Language',
    'generate.form.selectLanguage': 'Select language',
    'generate.form.subject': 'Course Subject',
    'generate.form.subjectPlaceholder': 'e.g. Project Management, Digital Marketing...',
    'generate.form.level': 'Course Level',
    'generate.form.selectLevel': 'Select level',
    'generate.form.beginner': 'Beginner',
    'generate.form.intermediate': 'Intermediate',
    'generate.form.advanced': 'Advanced',
    'generate.form.audience': 'Target Audience',
    'generate.form.selectAudience': 'Select audience',
    'generate.form.students': 'Students',
    'generate.form.professionals': 'Professionals',
    'generate.form.managers': 'Managers',
    'generate.form.duration': 'Course Duration',
    'generate.form.selectDuration': 'Select duration',
    'generate.form.30min': '30 minutes',
    'generate.form.1h': '1 hour',
    'generate.form.2h': '2 hours',
    'generate.form.4h': '4 hours',
    'generate.form.8h': '8 hours',
    'generate.form.tone': 'Course Tone',
    'generate.form.selectTone': 'Select tone',
    'generate.form.socratic': 'Socratic',
    'generate.form.energizing': 'Energizing',
    'generate.form.funny': 'Funny',
    'generate.form.professional': 'Professional',
    'generate.form.submit': 'Generate Course',
    'generate.form.submitting': 'Generating...',
    'generate.error.noGenerationsLeft': 'You have no courses left',
    'generate.error.upgradeOrWait': 'Upgrade your plan or wait for renewal',
    'generate.error.formIncomplete': 'Please fill in all fields',
    'generate.error.failed': 'Generation failed',
    'generate.success.started': 'Generation has started',
    'generate.info.timeEstimate': 'Generation can take 15-30 minutes',
    'generate.info.notification': 'You will be notified when materials are ready',
    'generate.info.remaining': 'Courses remaining',
    'generate.info.youHave': 'You have',
    'generate.info.generationsLeft': 'courses left in this cycle',
    'generate.info.courses': 'courses/month',
    
    // Progress - Updated for 7-step process
    'progress.title': 'Generation Progress',
    'progress.status': 'Status',
    'progress.created': 'Created at',
    'progress.pending': 'Pending',
    'progress.processing': 'Processing',
    'progress.completed': 'Completed',
    'progress.failed': 'Failed',
    'progress.retry': 'Retry',
    'progress.cancel': 'Cancel',
    'progress.viewMaterials': 'View Materials',
    'progress.viewProgress': 'View Progress',
    'progress.viewStatus': 'View Status',
    'progress.details': 'Generation Details',
    'progress.error': 'Error',
    'progress.step': 'Step',
    'progress.timeEstimate': 'Time Estimate',
    'progress.cancelled': 'Cancelled',
    'progress.jobCancelled': 'Generation was cancelled',
    'progress.retrying': 'Retrying',
    'progress.jobRetrying': 'Generation is retrying',
    'progress.confirmCancel': 'Are you sure you want to cancel the generation?',
    'progress.cancelFailed': 'Cancellation failed',
    'progress.retryFailed': 'Retry failed',
    'progress.generatingCourse': 'Generating course',
    'progress.step1': 'Structure + Objectives + Agenda',
    'progress.step2': 'Presentation Slides',
    'progress.step3': 'Facilitator Manual',
    'progress.step4': 'Participant Manual',
    'progress.step5': 'Activities and Exercises',
    'progress.step6': 'Evaluation Tools',
    'progress.step7': 'Additional Resources',
    
    // Materials - Updated for new file types
    'materials.title': 'Generated Materials',
    'materials.downloadAll': 'Download All',
    'materials.expiryNote': 'Download links expire in 72 hours',
    'materials.expiryWarning': 'Warning! Links expire soon',
    'materials.expiryDate': 'Expiry date',
    'materials.noMaterials': 'No materials available',
    'materials.regenerate': 'Regenerate',
    'materials.download': 'Download',
    'materials.preparing': 'Preparing',
    'materials.checkProgress': 'Check Progress',
    'materials.untitledCourse': 'Untitled Course',
    'materials.courseAgenda': 'Course agenda and structure',
    'materials.presentationSlides': 'Presentation slides',
    'materials.courseMaterial': 'Course material',
    'materials.noMaterialsDescription': 'Materials are still being generated. Check progress for more details.',
    'materials.types.foundation': 'Structure and Objectives',
    'materials.types.slides': 'Presentation Slides',
    'materials.types.facilitator': 'Facilitator Manual',
    'materials.types.participant': 'Participant Manual',
    'materials.types.activities': 'Activities and Exercises',
    'materials.types.evaluation': 'Evaluation Tools',
    'materials.types.resources': 'Additional Resources',
    
    // Settings
    'settings.title': 'Account Settings',
    'settings.description': 'Manage your account and subscription',
    'settings.account': 'Account',
    'settings.subscription': 'Subscription',
    'settings.security': 'Security',
    'settings.accountDetails': 'Account Details',
    'settings.accountDetailsDescription': 'Your basic account information',
    'settings.accountCreated': 'Account created',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm Password',
    'settings.updatePassword': 'Update Password',
    'settings.changePassword': 'Change Password',
    'settings.changePasswordDescription': 'Update your password for enhanced security',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountDescription': 'Permanently delete your account and all data',
    'settings.deleteAccountWarning': 'This action cannot be undone. All data will be permanently deleted.',
    'settings.warning': 'Warning',
    'settings.passwordUpdated': 'Password Updated',
    'settings.passwordUpdateSuccess': 'Password has been updated successfully',
    'settings.passwordUpdateError': 'Password Update Error',
    'settings.passwordUpdateFailed': 'Password update failed',
    
    // Subscription - Updated for new plans
    'subscription.free': 'Free',
    'subscription.basic': 'Basic',
    'subscription.pro': 'Pro',
    'subscription.enterprise': 'Enterprise',
    'subscription.monthly': '/month',
    'subscription.choosePlan': 'Choose a Plan',
    'subscription.currentPlan': 'Your Current Plan',
    'subscription.currentPlanDescription': 'Details of your current subscription',
    'subscription.features': 'Features',
    'subscription.upgrade': 'Upgrade',
    'subscription.downgrade': 'Downgrade',
    'subscription.cancel': 'Cancel',
    'subscription.switch': 'Switch',
    'subscription.manage': 'Manage Subscription',
    'subscription.availablePlans': 'Available Plans',
    'subscription.popular': 'Popular',
    'subscription.billingInfo': 'Billing Information',
    'subscription.billingManagedByStripe': 'Billing is managed through Stripe for maximum security',
    'subscription.confirmCancel': 'Are you sure you want to cancel your subscription?',
    'subscription.cancelSuccess': 'Subscription Cancelled',
    'subscription.cancelMessage': 'Your subscription has been cancelled successfully',
    'subscription.cancelError': 'Cancellation Error',
    'subscription.cancelFailed': 'Subscription cancellation failed',
    'subscription.upgradeError': 'Upgrade Error',
    'subscription.upgradeFailed': 'Subscription upgrade failed',
    'subscription.checkoutError': 'Checkout Error',
    'subscription.checkoutSuccess': 'Checkout Successful',
    'subscription.checkoutSuccessMessage': 'Your subscription has been updated successfully',
    'subscription.checkoutCancelled': 'Checkout Cancelled',
    'subscription.checkoutCancelledMessage': 'The payment process was cancelled',
    'subscription.renewsAutomatically': 'Renews automatically',
    'subscription.features.fullGeneration': 'Full course generation',
    'subscription.features.downloads': 'Unlimited downloads',
    'subscription.features.support': 'Standard support',
    'subscription.features.prioritySupport': 'Priority support',
    'subscription.features.dedicatedSupport': 'Dedicated support',
    'subscription.features.extendedDownloads': 'Extended downloads (7 days)',
    'subscription.features.priorityProcessing': 'Priority processing',
    
    // Plans - Updated for new pricing
    'plans.basic.name': 'Basic',
    'plans.basic.price': '€9',
    'plans.basic.description': '1 complete course/month',
    'plans.pro.name': 'Pro',
    'plans.pro.price': '€39',
    'plans.pro.description': '5 courses/month',
    'plans.enterprise.name': 'Enterprise',
    'plans.enterprise.price': '€89',
    'plans.enterprise.description': '20 courses/month',
    
    // Landing Page
    'landing.title': 'Optimized Course Generation System',
    'landing.subtitle': 'Create complete educational materials in 7 automated AI steps',
    'landing.aiPowered': 'AI-Powered',
    'landing.getStarted': 'Get Started',
    'landing.learnMore': 'Learn More',
    'landing.about': 'About',
    'landing.howItWorks': 'How It Works',
    'landing.howItWorksSubtitle': 'Our simple 3-step process for course generation',
    'landing.pricing': 'Pricing',
    'landing.pricingSubtitle': 'Choose the right plan for your needs',
    'landing.faq': 'FAQ',
    'landing.contact': 'Contact',
    'landing.footer.copyright': 'All rights reserved',
    'landing.footer.terms': 'Terms and Conditions',
    'landing.footer.privacy': 'Privacy Policy',
    'landing.step1Title': 'Configure Course',
    'landing.step1Description': 'Choose language, subject, level and duration',
    'landing.step2Title': 'AI Generates Materials',
    'landing.step2Description': 'Our system automatically creates all materials in 7 steps',
    'landing.step3Title': 'Download and Use',
    'landing.step3Description': 'Get complete materials ready to use',
    'landing.benefits': 'Platform Benefits',
    'landing.benefitsSubtitle': 'Why choose Automator.ro for your courses',
    'landing.benefit1Title': 'Save Time',
    'landing.benefit1Description': 'Generate complete courses in minutes, not days',
    'landing.benefit2Title': 'Professional Quality',
    'landing.benefit2Description': 'Materials created with industry standards',
    'landing.benefit3Title': '10 Languages Available',
    'landing.benefit3Description': 'Support for all major European languages',
    'landing.benefit4Title': 'For Any Audience',
    'landing.benefit4Description': 'Adaptable for students, professionals and managers',
    'landing.ctaTitle': 'Ready to get started?',
    'landing.ctaSubtitle': 'Join thousands of educators already using Automator.ro',
    'landing.startNow': 'Start Now',
    'landing.viewAllPlans': 'View All Plans',
    
    // About Page
    'about.title': 'About Automator.ro',
    'about.subtitle': 'Our mission and 7-step methodology',
    'about.mission.title': 'Our Mission',
    'about.mission.description1': 'Automator.ro transforms how educational materials are created, offering an AI platform that generates complete and professional courses in record time.',
    'about.mission.description2': 'We believe that quality education should be accessible and easy to create for all educators, regardless of their experience in instructional design.',
    'about.methodology.title': '7-Step Methodology',
    'about.methodology.subtitle': 'Our systematic process for creating complete courses',
    'about.step1Description': 'Defining course structure, learning objectives and detailed agenda',
    'about.step2Description': 'Creating presentation slides with visual content and presenter notes',
    'about.step3Description': 'Developing complete facilitator manual with guides and instructions',
    'about.step4Description': 'Generating participant manual with exercises and note spaces',
    'about.step5Description': 'Creating interactive activities, role plays and case studies',
    'about.step6Description': 'Developing evaluation tools for pre, during and post course',
    'about.step7Description': 'Compiling additional resources for continuous development',
    'about.whyChoose.title': 'Why Choose Automator.ro',
    'about.whyChoose.subtitle': 'Advantages that set us apart from other solutions',
    'about.advantage1.title': 'Speed',
    'about.advantage1.description': 'Generate complete courses in 15-30 minutes',
    'about.advantage2.title': 'Completeness',
    'about.advantage2.description': 'All necessary materials in one place',
    'about.advantage3.title': 'Multilingual',
    'about.advantage3.description': 'Support for 10 European languages',
    'about.advantage4.title': 'Customizable',
    'about.advantage4.description': 'Adapted for different audiences and levels',
    'about.advantage5.title': 'Professional',
    'about.advantage5.description': 'Industry standards in instructional design',
    'about.advantage6.title': 'Accessible',
    'about.advantage6.description': 'Competitive prices for all budgets',
    'about.cta.title': 'Start creating courses today',
    'about.cta.description': 'Join the community of educators using AI to create quality materials',
    'about.cta.startNow': 'Start Now',
    'about.cta.viewPricing': 'View Pricing',
    
    // Pricing Page
    'pricing.title': 'Plans and Pricing',
    'pricing.subtitle': 'Choose the right plan for your educational needs',
    'pricing.feature.allLanguages': 'All 10 languages',
    'pricing.faq.title': 'Frequently Asked Questions',
    'pricing.faq.subtitle': 'Answers to common questions about plans',
    'pricing.faq.q1': 'Can I change my plan anytime?',
    'pricing.faq.a1': 'Yes, you can upgrade or downgrade your plan anytime. Changes apply immediately.',
    'pricing.faq.q2': 'What happens if I exceed my course limit?',
    'pricing.faq.a2': 'You\'ll be notified when approaching the limit. You can upgrade for additional courses.',
    'pricing.faq.q3': 'Are there discounts for institutions?',
    'pricing.faq.a3': 'Yes, we offer special discounts for schools and universities. Contact us for details.',
    'pricing.faq.q4': 'Can I cancel my subscription anytime?',
    'pricing.faq.a4': 'Yes, you can cancel your subscription anytime. No penalties or cancellation fees.',
    'pricing.contact.title': 'Need a custom plan?',
    'pricing.contact.description': 'Contact us for enterprise solutions or custom plans',
    'pricing.contact.button': 'Contact Us',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We\'re here to help with any questions or suggestions',
    'contact.info.email': 'Email',
    'contact.info.emailDescription': 'Send us an email for general inquiries',
    'contact.info.phone': 'Phone',
    'contact.info.phoneDescription': 'Call us for urgent support',
    'contact.info.address': 'Address',
    'contact.info.addressDescription': 'Our office in Bucharest',
    'contact.form.title': 'Send us a message',
    'contact.form.description': 'Fill out the form and we\'ll get back to you as soon as possible',
    'contact.form.name': 'Name',
    'contact.form.namePlaceholder': 'Your full name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'What would you like to discuss?',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Describe your question or suggestion...',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message Sent',
    'contact.form.successMessage': 'Thank you for your message. We\'ll get back to you soon.',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.subtitle': 'Quick answers to common questions',
    'contact.faq.q1': 'How long does it take to generate a course?',
    'contact.faq.a1': 'Course generation takes between 15-30 minutes, depending on complexity.',
    'contact.faq.q2': 'Can I edit the generated materials?',
    'contact.faq.a2': 'Yes, all materials are editable and can be customized to your needs.',
    'contact.faq.q3': 'In what formats do I receive the materials?',
    'contact.faq.a3': 'Materials are available in DOCX format for texts and PPTX for presentations.',
    
    // 404 Page
    '404.title': 'Page Not Found',
    '404.description': 'Sorry, the page you\'re looking for doesn\'t exist.',
    '404.suggestion': 'You might have mistyped the address or the page has been moved.',
    '404.goHome': 'Go Home',
    '404.contact': 'Contact Us',
    '404.goBack': 'Go Back',
    
    // Languages
    'languages.ro': 'Română',
    'languages.en': 'English',
    'languages.fr': 'Français',
    'languages.de': 'Deutsch',
    'languages.es': 'Español',
    'languages.it': 'Italiano',
    'languages.pt': 'Português',
    'languages.nl': 'Nederlands',
    'languages.sv': 'Svenska',
    'languages.da': 'Dansk',
  }
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Get initial language from local storage or default to Romanian
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language');
    return (savedLanguage && ['ro', 'en', 'fr', 'de', 'es', 'it', 'pt', 'nl', 'sv', 'da'].includes(savedLanguage) 
      ? savedLanguage as Language 
      : 'ro');
  });

  // Update language and save to local storage
  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  }, []);

  // Translation function
  const t = useCallback((key: string) => {
    const currentTranslations = translations[language] || translations.ro;
    return currentTranslations[key as keyof typeof currentTranslations] || key;
  }, [language]);

  const value = {
    language,
    setLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context.t;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}